version: '3.8'

services:
  nzb4:
    build:
      context: .
      dockerfile: Dockerfile
    image: nzb4:latest
    container_name: nzb4
    restart: unless-stopped
    ports:
      - "8000:8000"  # Web UI
      - "5678:5678"  # N8N
    volumes:
      - ./data:/data
      - ./config.json:/app/config.json:ro
    environment:
      - DOWNLOADS_DIR=/data/downloads
      - COMPLETE_DIR=/data/complete
      - TEMP_DIR=/data/temp
      - MOVIES_DIR=/data/complete/movies
      - TV_DIR=/data/complete/tv
      - MUSIC_DIR=/data/complete/music 
      - OTHER_DIR=/data/complete/other
      - N8N_DATA_FOLDER=/data/n8n
      - WEB_PORT=8000
      - N8N_PORT=5678
      - N8N_ENABLED=true
      - TZ=UTC
    networks:
      - nzb4_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nzb4-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: nzb4:latest
    container_name: nzb4-worker
    restart: unless-stopped
    command: worker
    volumes:
      - ./data:/data
      - ./config.json:/app/config.json:ro
    environment:
      - DOWNLOADS_DIR=/data/downloads
      - COMPLETE_DIR=/data/complete
      - TEMP_DIR=/data/temp
      - MOVIES_DIR=/data/complete/movies
      - TV_DIR=/data/complete/tv
      - MUSIC_DIR=/data/complete/music 
      - OTHER_DIR=/data/complete/other
      - N8N_ENABLED=false
      - TZ=UTC
    networks:
      - nzb4_network
    depends_on:
      - nzb4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nzb4_network:
    driver: bridge

volumes:
  data:
    driver: local 